version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: taskvault_postgres_db
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskvaultdb
    ports:
      - "5432:5432"
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
