version: '3.8'

services:
  spring_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - spring_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://spring_db:3306/taskvaultdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password

  spring_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: taskvaultdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
